/* 
 * dataintegrationapi
 *
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloudmersive.APIClient.NET.DataIntegration.Client;
using Cloudmersive.APIClient.NET.DataIntegration.Model;

namespace Cloudmersive.APIClient.NET.DataIntegration.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBackupConvertApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>MssqlBakEnumerateTablesResult</returns>
        MssqlBakEnumerateTablesResult DataintegrationBackupConvertMssqlBakGetTablesPost (System.IO.Stream inputFile = null);

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>ApiResponse of MssqlBakEnumerateTablesResult</returns>
        ApiResponse<MssqlBakEnumerateTablesResult> DataintegrationBackupConvertMssqlBakGetTablesPostWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table
        /// </summary>
        /// <remarks>
        /// Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>byte[]</returns>
        byte[] DataintegrationBackupConvertMssqlBakToCsvPost (string tableName = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table
        /// </summary>
        /// <remarks>
        /// Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> DataintegrationBackupConvertMssqlBakToCsvPostWithHttpInfo (string tableName = null, System.IO.Stream inputFile = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of MssqlBakEnumerateTablesResult</returns>
        System.Threading.Tasks.Task<MssqlBakEnumerateTablesResult> DataintegrationBackupConvertMssqlBakGetTablesPostAsync (System.IO.Stream inputFile = null);

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of ApiResponse (MssqlBakEnumerateTablesResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<MssqlBakEnumerateTablesResult>> DataintegrationBackupConvertMssqlBakGetTablesPostAsyncWithHttpInfo (System.IO.Stream inputFile = null);
        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table
        /// </summary>
        /// <remarks>
        /// Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> DataintegrationBackupConvertMssqlBakToCsvPostAsync (string tableName = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table
        /// </summary>
        /// <remarks>
        /// Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> DataintegrationBackupConvertMssqlBakToCsvPostAsyncWithHttpInfo (string tableName = null, System.IO.Stream inputFile = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BackupConvertApi : IBackupConvertApi
    {
        private Cloudmersive.APIClient.NET.DataIntegration.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BackupConvertApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BackupConvertApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackupConvertApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BackupConvertApi(Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.DataIntegration.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.DataIntegration.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>MssqlBakEnumerateTablesResult</returns>
        public MssqlBakEnumerateTablesResult DataintegrationBackupConvertMssqlBakGetTablesPost (System.IO.Stream inputFile = null)
        {
             ApiResponse<MssqlBakEnumerateTablesResult> localVarResponse = DataintegrationBackupConvertMssqlBakGetTablesPostWithHttpInfo(inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>ApiResponse of MssqlBakEnumerateTablesResult</returns>
        public ApiResponse< MssqlBakEnumerateTablesResult > DataintegrationBackupConvertMssqlBakGetTablesPostWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "/dataintegration/backup/convert/mssql/bak/get/tables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DataintegrationBackupConvertMssqlBakGetTablesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MssqlBakEnumerateTablesResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MssqlBakEnumerateTablesResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MssqlBakEnumerateTablesResult)));
        }

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of MssqlBakEnumerateTablesResult</returns>
        public async System.Threading.Tasks.Task<MssqlBakEnumerateTablesResult> DataintegrationBackupConvertMssqlBakGetTablesPostAsync (System.IO.Stream inputFile = null)
        {
             ApiResponse<MssqlBakEnumerateTablesResult> localVarResponse = await DataintegrationBackupConvertMssqlBakGetTablesPostAsyncWithHttpInfo(inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists all tables stored in a SQL Server Backup (.BAK) file 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of ApiResponse (MssqlBakEnumerateTablesResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MssqlBakEnumerateTablesResult>> DataintegrationBackupConvertMssqlBakGetTablesPostAsyncWithHttpInfo (System.IO.Stream inputFile = null)
        {

            var localVarPath = "/dataintegration/backup/convert/mssql/bak/get/tables";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DataintegrationBackupConvertMssqlBakGetTablesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MssqlBakEnumerateTablesResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MssqlBakEnumerateTablesResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MssqlBakEnumerateTablesResult)));
        }

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] DataintegrationBackupConvertMssqlBakToCsvPost (string tableName = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = DataintegrationBackupConvertMssqlBakToCsvPostWithHttpInfo(tableName, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > DataintegrationBackupConvertMssqlBakToCsvPostWithHttpInfo (string tableName = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "/dataintegration/backup/convert/mssql/bak/to/csv";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/csv"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tableName != null) localVarHeaderParams.Add("tableName", this.Configuration.ApiClient.ParameterToString(tableName)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DataintegrationBackupConvertMssqlBakToCsvPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> DataintegrationBackupConvertMssqlBakToCsvPostAsync (string tableName = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<byte[]> localVarResponse = await DataintegrationBackupConvertMssqlBakToCsvPostAsyncWithHttpInfo(tableName, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Converts a SQL Server Backup (.BAK) file into CSV for a specified table Input the target table to extract the data as a CSV format file.  Supports a wide array of SQL Server .BAK files and SQL Server backup file versions.  Consumes 1 API call per MB of input data.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.DataIntegration.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tableName">Name of the table to return (optional)</param>
        /// <param name="inputFile">Input file to perform the operation on (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> DataintegrationBackupConvertMssqlBakToCsvPostAsyncWithHttpInfo (string tableName = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "/dataintegration/backup/convert/mssql/bak/to/csv";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/csv"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tableName != null) localVarHeaderParams.Add("tableName", this.Configuration.ApiClient.ParameterToString(tableName)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DataintegrationBackupConvertMssqlBakToCsvPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

    }
}
