/* 
 * dataintegrationapi
 *
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DataIntegration.Api;
using Cloudmersive.APIClient.NET.DataIntegration.Model;
using Cloudmersive.APIClient.NET.DataIntegration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DataIntegration.Test
{
    /// <summary>
    ///  Class for testing MssqlTable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MssqlTableTests
    {
        // TODO uncomment below to declare an instance variable for MssqlTable
        //private MssqlTable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MssqlTable
            //instance = new MssqlTable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MssqlTable
        /// </summary>
        [Test]
        public void MssqlTableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MssqlTable
            //Assert.IsInstanceOfType<MssqlTable> (instance, "variable 'instance' is a MssqlTable");
        }


        /// <summary>
        /// Test the property 'SchemaName'
        /// </summary>
        [Test]
        public void SchemaNameTest()
        {
            // TODO unit test for the property 'SchemaName'
        }
        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Test]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }

    }

}
