/* 
 * dataintegrationapi
 *
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DataIntegration.Api;
using Cloudmersive.APIClient.NET.DataIntegration.Model;
using Cloudmersive.APIClient.NET.DataIntegration.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DataIntegration.Test
{
    /// <summary>
    ///  Class for testing MssqlBakEnumerateTablesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MssqlBakEnumerateTablesResultTests
    {
        // TODO uncomment below to declare an instance variable for MssqlBakEnumerateTablesResult
        //private MssqlBakEnumerateTablesResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MssqlBakEnumerateTablesResult
            //instance = new MssqlBakEnumerateTablesResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MssqlBakEnumerateTablesResult
        /// </summary>
        [Test]
        public void MssqlBakEnumerateTablesResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MssqlBakEnumerateTablesResult
            //Assert.IsInstanceOfType<MssqlBakEnumerateTablesResult> (instance, "variable 'instance' is a MssqlBakEnumerateTablesResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'Tables'
        /// </summary>
        [Test]
        public void TablesTest()
        {
            // TODO unit test for the property 'Tables'
        }

    }

}
