/* 
 * dataintegrationapi
 *
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.DataIntegration.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.DataIntegration.Model
{
    /// <summary>
    /// Result of enumeerating Tables in a SQL Server Backup (.BAK) file
    /// </summary>
    [DataContract]
    public partial class MssqlBakEnumerateTablesResult :  IEquatable<MssqlBakEnumerateTablesResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MssqlBakEnumerateTablesResult" /> class.
        /// </summary>
        /// <param name="successful">True if successful, False otherwise.</param>
        /// <param name="tables">SQL Server Tables in the backup file.</param>
        public MssqlBakEnumerateTablesResult(bool? successful = default(bool?), List<MssqlTable> tables = default(List<MssqlTable>))
        {
            this.Successful = successful;
            this.Tables = tables;
        }
        
        /// <summary>
        /// True if successful, False otherwise
        /// </summary>
        /// <value>True if successful, False otherwise</value>
        [DataMember(Name="successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// SQL Server Tables in the backup file
        /// </summary>
        /// <value>SQL Server Tables in the backup file</value>
        [DataMember(Name="tables", EmitDefaultValue=false)]
        public List<MssqlTable> Tables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MssqlBakEnumerateTablesResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Tables: ").Append(Tables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MssqlBakEnumerateTablesResult);
        }

        /// <summary>
        /// Returns true if MssqlBakEnumerateTablesResult instances are equal
        /// </summary>
        /// <param name="input">Instance of MssqlBakEnumerateTablesResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MssqlBakEnumerateTablesResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.Tables == input.Tables ||
                    this.Tables != null &&
                    this.Tables.SequenceEqual(input.Tables)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.Tables != null)
                    hashCode = hashCode * 59 + this.Tables.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
